version: '3'

services:
  vmsm:
    build:
      context: .
      dockerfile: Dockerfile
    image: cmillani/vmsm
    container_name: vmsm
    ports:
      - "5000:5000"
    environment:
      - CONNSTRING=qemu+ssh://carlos@192.168.1.6/system?keyfile=/home/carlos/.ssh/id_rsa
      - VMNAME=debtest